import React from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import "../worldcup-pool.css";

import type { Lang } from "../../i18n";
import { coercePublicLang } from "../lib/publicLang";
import {
  fetchWorldCupPoolInvite,
  fetchWorldCupPoolMyPools, 
  joinWorldCupPool,
  loginWorldCupPoolParticipant,
  requestWorldCupPoolPinReset,
  type WorldCupPoolInviteResponse,
  type WorldCupPoolJoinResponse,
} from "../api/publicClient";

type AccessMode = "join" | "login";

const COPY = {
  pt: {
    loading: "Carregando convite...",
    notFoundTitle: "Convite não encontrado",
    notFoundBody:
      "Este link pode ter expirado, sido recriado pelo organizador ou digitado incorretamente.",
    eyebrow: "Convite recebido",
    titlePrefix: "Entrar no bolão",
    participantCount: "participantes confirmados",
    body:
      "Este link é a entrada deste bolão. Você pode participar pela primeira vez ou entrar novamente com e-mail e PIN.",
    joinTab: "Participar",
    loginTab: "Já participo",
    joinTitle: "Primeira vez neste bolão",
    loginTitle: "Entrar novamente",
    joinBody:
      "Crie sua participação com nome no ranking, e-mail e PIN de 4 dígitos.",
    loginBody:
      "Se você já participa deste bolão, entre com o mesmo e-mail e PIN.",
    displayName: "Seu nome no ranking",
    email: "E-mail",
    pin: "PIN de 4 dígitos",
    displayNamePlaceholder: "Ex: Tiago",
    emailPlaceholder: "voce@email.com",
    pinPlaceholder: "1234",
    terms:
      "Aceito participar de um bolão sem fins financeiros, apenas para diversão e ranking entre amigos.",
    marketing: "Quero receber novidades do prevIA e do Bolão da Copa.",
    submitJoin: "Participar do bolão",
    submitLogin: "Entrar no bolão",
    sending: "Entrando...",
    successTitle: "Você entrou no bolão!",
    successBody:
      "No próximo passo, vamos liberar a tela de palpites da fase de grupos.",
    existingLogin:
      "Identificamos seu e-mail e validamos seu PIN. Você voltou para este bolão.",
    newJoin: "Sua participação foi confirmada.",
    backToLanding: "Ver página do Bolão da Copa",
    errorJoin:
      "Não foi possível participar agora. Confira os dados, principalmente o PIN se esse e-mail já estiver cadastrado.",
    errorLogin:
      "Não foi possível entrar. Confira se este e-mail já participa deste bolão e se o PIN está correto.",
    pinHelpJoin:
      "Use apenas números. Guarde esse PIN para acessar depois em outro celular.",
    pinHelpLogin:
      "Use o PIN criado quando você entrou neste bolão.",
    forgotPin: "Esqueci meu PIN",
    pinResetSending: "Enviando...",
    pinResetSent:
      "Se este e-mail estiver vinculado a este bolão, enviaremos um novo PIN e o link de acesso.",
    pinResetEmailRequired: "Informe seu e-mail para recuperar o PIN.",
    pinResetError: "Não foi possível enviar o novo PIN agora. Tente novamente em instantes.",
    joinDisabled:
      "A entrada de participantes ainda não está liberada para este bolão.",
  },
  en: {
    loading: "Loading invite...",
    notFoundTitle: "Invite not found",
    notFoundBody:
      "This link may have expired, been regenerated by the organizer, or typed incorrectly.",
    eyebrow: "Invitation received",
    titlePrefix: "Join pool",
    participantCount: "confirmed participants",
    body:
      "This link is the entry point for this pool. You can join for the first time or return with email and PIN.",
    joinTab: "Join",
    loginTab: "I already joined",
    joinTitle: "First time in this pool",
    loginTitle: "Sign back in",
    joinBody:
      "Create your participation with leaderboard name, email, and a 4-digit PIN.",
    loginBody:
      "If you already joined this pool, sign in with the same email and PIN.",
    displayName: "Your leaderboard name",
    email: "Email",
    pin: "4-digit PIN",
    displayNamePlaceholder: "Ex: Tiago",
    emailPlaceholder: "you@email.com",
    pinPlaceholder: "1234",
    terms:
      "I agree to join a pool with no financial purpose, only for fun and a friends ranking.",
    marketing: "I want to receive prevIA and World Cup Pool updates.",
    submitJoin: "Join pool",
    submitLogin: "Enter pool",
    sending: "Entering...",
    successTitle: "You entered the pool!",
    successBody:
      "Next, we will unlock the group-stage prediction screen.",
    existingLogin:
      "We found your email and validated your PIN. You are back in this pool.",
    newJoin: "Your participation has been confirmed.",
    backToLanding: "View World Cup Pool page",
    errorJoin:
      "Could not join right now. Check the fields, especially the PIN if this email is already registered.",
    errorLogin:
      "Could not sign in. Check whether this email already joined this pool and whether the PIN is correct.",
    pinHelpJoin:
      "Use numbers only. Keep this PIN to access later from another device.",
    pinHelpLogin:
      "Use the PIN you created when you joined this pool.",
    forgotPin: "I forgot my PIN",
    pinResetSending: "Sending...",
    pinResetSent:
      "If this email is linked to this pool, we will send a new PIN and access link.",
    pinResetEmailRequired: "Enter your email to recover your PIN.",
    pinResetError: "Could not send a new PIN right now. Try again in a moment.",
    joinDisabled:
      "Participant entry is not enabled for this pool yet.",
  },
  es: {
    loading: "Cargando invitación...",
    notFoundTitle: "Invitación no encontrada",
    notFoundBody:
      "Este enlace puede haber expirado, haber sido regenerado por el organizador o estar mal escrito.",
    eyebrow: "Invitación recibida",
    titlePrefix: "Entrar en la porra",
    participantCount: "participantes confirmados",
    body:
      "Este enlace es la entrada de esta porra. Puedes participar por primera vez o volver con email y PIN.",
    joinTab: "Participar",
    loginTab: "Ya participo",
    joinTitle: "Primera vez en esta porra",
    loginTitle: "Entrar nuevamente",
    joinBody:
      "Crea tu participación con nombre en el ranking, email y PIN de 4 dígitos.",
    loginBody:
      "Si ya participas en esta porra, entra con el mismo email y PIN.",
    displayName: "Tu nombre en el ranking",
    email: "Email",
    pin: "PIN de 4 dígitos",
    displayNamePlaceholder: "Ej: Tiago",
    emailPlaceholder: "tu@email.com",
    pinPlaceholder: "1234",
    terms:
      "Acepto participar en una porra sin fines financieros, solo para diversión y ranking entre amigos.",
    marketing: "Quiero recibir novedades de prevIA y de la Porra del Mundial.",
    submitJoin: "Participar en la porra",
    submitLogin: "Entrar en la porra",
    sending: "Entrando...",
    successTitle: "¡Entraste en la porra!",
    successBody:
      "En el próximo paso, liberaremos la pantalla de pronósticos de la fase de grupos.",
    existingLogin:
      "Identificamos tu email y validamos tu PIN. Volviste a esta porra.",
    newJoin: "Tu participación fue confirmada.",
    backToLanding: "Ver página de la Porra del Mundial",
    errorJoin:
      "No fue posible participar ahora. Revisa los datos, especialmente el PIN si este email ya está registrado.",
    errorLogin:
      "No fue posible entrar. Revisa si este email ya participa en esta porra y si el PIN es correcto.",
    pinHelpJoin:
      "Usa solo números. Guarda este PIN para acceder luego desde otro dispositivo.",
    pinHelpLogin:
      "Usa el PIN que creaste cuando entraste en esta porra.",
    forgotPin: "Olvidé mi PIN",
    pinResetSending: "Enviando...",
    pinResetSent:
      "Si este email está vinculado a esta porra, enviaremos un nuevo PIN y el enlace de acceso.",
    pinResetEmailRequired: "Informa tu email para recuperar el PIN.",
    pinResetError: "No fue posible enviar el nuevo PIN ahora. Inténtalo nuevamente en unos instantes.",
    joinDisabled:
      "La entrada de participantes aún no está liberada para esta porra.",
  },
} as const;

export function WorldCupPoolJoinPlaceholderPage() {
  const { lang, inviteToken } = useParams<{ lang: string; inviteToken: string }>();
  const currentLang = coercePublicLang(lang) as Lang;
  const copy = COPY[currentLang] ?? COPY.pt;
  const token = String(inviteToken || "").trim();
  const navigate = useNavigate();

  const [invite, setInvite] = React.useState<WorldCupPoolInviteResponse | null>(null);
  const [loadError, setLoadError] = React.useState(false);
  const [loading, setLoading] = React.useState(true);

  const [mode, setMode] = React.useState<AccessMode>("join");
  const [displayName, setDisplayName] = React.useState("");
  const [email, setEmail] = React.useState("");
  const [pin, setPin] = React.useState("");
  const [termsAccepted, setTermsAccepted] = React.useState(false);
  const [marketingOptIn, setMarketingOptIn] = React.useState(false);

  const [busy, setBusy] = React.useState(false);
  const [error, setError] = React.useState("");
  const [joined, setJoined] = React.useState<WorldCupPoolJoinResponse | null>(null);
  const [pinResetBusy, setPinResetBusy] = React.useState(false);
  const [pinResetMessage, setPinResetMessage] = React.useState("");
  const [pinResetError, setPinResetError] = React.useState("");

  React.useEffect(() => {
    let cancelled = false;

    async function load() {
      if (!token) {
        setLoadError(true);
        setLoading(false);
        return;
      }

      try {
        const data = await fetchWorldCupPoolInvite(token);
        if (!cancelled) {
          setInvite(data);
          setLoadError(false);
        }
      } catch (err) {
        console.error("failed to load world cup pool invite", err);
        if (!cancelled) {
          setLoadError(true);
        }
      } finally {
        if (!cancelled) {
          setLoading(false);
        }
      }
    }

    void load();

    return () => {
      cancelled = true;
    };
  }, [token]);

  const pinIsValid = /^\d{4}$/.test(pin);

  const joinDisabled =
    busy ||
    !invite?.join_enabled ||
    !displayName.trim() ||
    !email.trim() ||
    !pinIsValid ||
    !termsAccepted;

  const loginDisabled =
    busy ||
    !invite?.join_enabled ||
    !email.trim() ||
    !pinIsValid;

  const disabled = mode === "join" ? joinDisabled : loginDisabled;

  function onPinChange(value: string) {
    setPin(value.replace(/\D/g, "").slice(0, 4));
  }

  function onModeChange(nextMode: AccessMode) {
    setMode(nextMode);
    setError("");
    setJoined(null);
    setPinResetMessage("");
    setPinResetError("");
  }

  async function onPinReset() {
    if (!email.trim()) {
      setPinResetMessage("");
      setPinResetError(copy.pinResetEmailRequired);
      return;
    }

    setPinResetBusy(true);
    setPinResetMessage("");
    setPinResetError("");

    try {
      await requestWorldCupPoolPinReset({
        email: email.trim(),
        invite_token: token,
      });

      setPinResetMessage(copy.pinResetSent);
    } catch (err) {
      console.error("failed to request world cup pool pin reset", err);
      setPinResetError(copy.pinResetError);
    } finally {
      setPinResetBusy(false);
    }
  }

  async function onSubmit(event: React.FormEvent) {
    event.preventDefault();

    if (disabled || !token) return;

    setBusy(true);
    setError("");
    setJoined(null);

    try {
      const response =
        mode === "login"
          ? await loginWorldCupPoolParticipant(token, {
              email: email.trim(),
              pin,
            })
          : await joinWorldCupPool(token, {
              display_name: displayName.trim(),
              email: email.trim(),
              pin,
              marketing_opt_in: marketingOptIn,
              terms_accepted: termsAccepted,
            });

      setJoined(response);

      const myPools = await fetchWorldCupPoolMyPools();

      if (myPools.pools.length > 1) {
        navigate(`/${currentLang}/bolao/copa/meus-boloes`, { replace: true });
        return;
      }
      
      navigate(`/${currentLang}/bolao/copa/painel/${encodeURIComponent(token)}`, { replace: true });
    } catch (err) {
      console.error("failed to access world cup pool", err);
      setError(mode === "login" ? copy.errorLogin : copy.errorJoin);
    } finally {
      setBusy(false);
    }
  }

  if (loading) {
    return (
      <div className="worldcup-pool-page">
        <section className="worldcup-pool-hero">
          <div className="worldcup-pool-hero-card worldcup-pool-placeholder-card">
            <p className="public-body">{copy.loading}</p>
          </div>
        </section>
      </div>
    );
  }

  if (loadError || !invite) {
    return (
      <div className="worldcup-pool-page">
        <section className="worldcup-pool-hero">
          <div className="worldcup-pool-hero-card worldcup-pool-placeholder-card">
            <div>
              <div className="public-eyebrow">{copy.eyebrow}</div>
              <h1 className="public-title">{copy.notFoundTitle}</h1>
              <p className="public-body">{copy.notFoundBody}</p>
            </div>
          </div>
        </section>
      </div>
    );
  }

  if (joined) {
    return (
      <div className="worldcup-pool-page">
        <section className="worldcup-pool-hero">
          <div className="worldcup-pool-hero-card worldcup-pool-placeholder-card">
            <div className="worldcup-pool-create-result">
              <div>
                <div className="public-eyebrow">{copy.successTitle}</div>
                <h1>{joined.pool.name}</h1>
                <p>{joined.participant.joined_existing ? copy.existingLogin : copy.newJoin}</p>
                <p>{copy.successBody}</p>
              </div>

              <div className="worldcup-pool-created-link">
                <span>{joined.participant.display_name}</span>
              </div>

              <Link className="public-btn public-btn-secondary" to={`/${currentLang}/bolao/copa`}>
                {copy.backToLanding}
              </Link>
            </div>
          </div>
        </section>
      </div>
    );
  }

  return (
    <div className="worldcup-pool-page">
      <section className="worldcup-pool-hero">
        <div className="worldcup-pool-hero-card">
          <div>
            <div className="public-eyebrow">{copy.eyebrow}</div>
            <h1 className="public-title">
              {copy.titlePrefix}: {invite.pool.name}
            </h1>
            <p className="public-body">{copy.body}</p>

            <div className="worldcup-pool-token-preview">
              <span>{invite.pool.participant_count}</span>
              <strong>{copy.participantCount}</strong>
            </div>

            {!invite.join_enabled ? (
              <p className="worldcup-pool-hero-note">{copy.joinDisabled}</p>
            ) : null}
          </div>

          <form className="worldcup-pool-form worldcup-pool-create-form" onSubmit={onSubmit}>
            <div className="worldcup-pool-access-tabs" role="tablist" aria-label={copy.titlePrefix}>
              <button
                type="button"
                className={`worldcup-pool-access-tab ${mode === "join" ? "is-active" : ""}`}
                onClick={() => onModeChange("join")}
                aria-pressed={mode === "join"}
              >
                {copy.joinTab}
              </button>

              <button
                type="button"
                className={`worldcup-pool-access-tab ${mode === "login" ? "is-active" : ""}`}
                onClick={() => onModeChange("login")}
                aria-pressed={mode === "login"}
              >
                {copy.loginTab}
              </button>
            </div>

            <div className="worldcup-pool-access-mode-head">
              <h3>{mode === "join" ? copy.joinTitle : copy.loginTitle}</h3>
              <p>{mode === "join" ? copy.joinBody : copy.loginBody}</p>
            </div>

            {mode === "join" ? (
              <label className="product-field">
                <span>{copy.displayName}</span>
                <input
                  value={displayName}
                  onChange={(event) => setDisplayName(event.target.value)}
                  placeholder={copy.displayNamePlaceholder}
                  autoComplete="name"
                  disabled={busy || !invite.join_enabled}
                />
              </label>
            ) : null}

            <label className="product-field">
              <span>{copy.email}</span>
              <input
                type="email"
                value={email}
                onChange={(event) => setEmail(event.target.value)}
                placeholder={copy.emailPlaceholder}
                autoComplete="email"
                disabled={busy || !invite.join_enabled}
              />
            </label>

            <label className="product-field">
              <span>{copy.pin}</span>
              <input
                type="text"
                inputMode="numeric"
                value={pin}
                onChange={(event) => onPinChange(event.target.value)}
                placeholder={copy.pinPlaceholder}
                autoComplete="one-time-code"
                disabled={busy || !invite.join_enabled}
              />
            </label>

            <p className="worldcup-pool-pin-help">
              {mode === "join" ? copy.pinHelpJoin : copy.pinHelpLogin}
            </p>

            <div className="worldcup-pool-pin-reset-row">
              <button
                type="button"
                className="worldcup-pool-link-button"
                onClick={onPinReset}
                disabled={pinResetBusy || busy || !invite.join_enabled}
              >
                {pinResetBusy ? copy.pinResetSending : copy.forgotPin}
              </button>
            </div>

            {pinResetMessage ? (
              <p className="worldcup-pool-form-success">{pinResetMessage}</p>
            ) : null}

            {pinResetError ? (
              <p className="worldcup-pool-form-error">{pinResetError}</p>
            ) : null}

            {mode === "join" ? (
              <div className="worldcup-pool-consents">
                <div className="worldcup-pool-consent-row">
                  <input
                    id="worldcup-pool-join-terms"
                    type="checkbox"
                    checked={termsAccepted}
                    onChange={(event) => setTermsAccepted(event.target.checked)}
                    disabled={busy || !invite.join_enabled}
                  />

                  <label className="worldcup-pool-consent-text" htmlFor="worldcup-pool-join-terms">
                    {copy.terms}
                  </label>
                </div>

                <div className="worldcup-pool-consent-row">
                  <input
                    id="worldcup-pool-join-marketing"
                    type="checkbox"
                    checked={marketingOptIn}
                    onChange={(event) => setMarketingOptIn(event.target.checked)}
                    disabled={busy || !invite.join_enabled}
                  />

                  <label
                    className="worldcup-pool-consent-text"
                    htmlFor="worldcup-pool-join-marketing"
                  >
                    {copy.marketing}
                  </label>
                </div>
              </div>
            ) : null}

            <button type="submit" className="public-btn public-btn-primary" disabled={disabled}>
              {busy ? copy.sending : mode === "join" ? copy.submitJoin : copy.submitLogin}
            </button>

            {error ? <div className="beta-form-error">{error}</div> : null}
          </form>
        </div>
      </section>
    </div>
  );
}