import type { Lang } from "../../../../../i18n";
import type { GlossaryTermEnhancement } from "../../glossaryData";

export const modelProbabilityEnhancement: Partial<
  Record<Lang, GlossaryTermEnhancement>
> = {
  pt: {
    seoTitle: "Probabilidade do modelo: como uma estimativa estatística ajuda nas apostas",
    seoDescription: "Entenda o que é probabilidade do modelo, como ela difere da odd da casa e por que é útil para comparar preço, risco e valor.",
    intro: "Probabilidade do modelo é a estimativa gerada por uma camada estatística ou analítica. Em vez de simplesmente aceitar a odd da casa, ela cria uma leitura própria sobre a chance de cada resultado.",
    sections: [
      {
        title: "Como um modelo gera probabilidade",
        body: [
          "Um modelo pode usar dados de desempenho, força dos times, mando de campo, gols esperados, histórico, forma recente e outros fatores. O objetivo é transformar informações em uma estimativa percentual.",
          "Essa estimativa não precisa ser perfeita para ser útil. Ela precisa ser consistente, comparável e testável ao longo do tempo.",
        ],
      },
      {
        title: "Modelo versus mercado",
        body: [
          "A casa publica preço. O modelo estima chance. Quando a probabilidade do modelo difere da probabilidade implícita da odd, nasce uma oportunidade de análise: o mercado pode estar caro, barato ou alinhado.",
        ],
      },
      {
        title: "Erro comum",
        body: [
          "O erro comum é tratar o modelo como oráculo. Modelos erram, precisam ser calibrados e devem ser interpretados com contexto.",
        ],
      },
    ],
    productNote: "No prevIA, a probabilidade estimada é uma das bases para gerar odd justa, comparar com odds disponíveis e organizar a leitura de valor.",
    faq: [
      {
        question: "Probabilidade do modelo garante o resultado?",
        answer: "Não. Ela é uma estimativa probabilística, não uma previsão determinística.",
      },
      {
        question: "Por que comparar modelo com mercado?",
        answer: "Porque a diferença entre estimativa e preço pode revelar possíveis distorções, oportunidades ou riscos.",
      },
    ],
  },

  en: {
    seoTitle: "Model probability: how statistical estimates support betting analysis",
    seoDescription:
      "Understand model probability, how it differs from bookmaker odds, and why it helps compare price, risk, and value.",
    intro:
      "Model probability is an estimate generated by a statistical or analytical layer. It creates an independent view of event chances.",
    sections: [
      {
        title: "How models estimate probability",
        body: [
          "A model can use performance data, team strength, home advantage, expected goals, recent form, and other factors.",
          "The goal is not perfection, but consistent, comparable, and testable estimates.",
        ],
      },
      {
        title: "Model versus market",
        body: [
          "The bookmaker publishes price. The model estimates chance. Differences between the two create analysis opportunities.",
        ],
      },
      {
        title: "Common mistake",
        body: [
          "A common mistake is treating a model as an oracle. Models need calibration and context.",
        ],
      },
    ],
    productNote:
      "In prevIA, estimated probability is a base for fair odds and value reading.",
    faq: [
      {
        question: "Does model probability guarantee outcomes?",
        answer:
          "No. It is probabilistic, not deterministic.",
      },
      {
        question: "Why compare model and market?",
        answer:
          "Because gaps can reveal possible distortions, value, or risk.",
      },
    ],
  },

  es: {
    seoTitle: "Probabilidad del modelo: cómo una estimación estadística ayuda",
    seoDescription:
      "Entiende probabilidad del modelo, cómo difiere de la cuota de la casa y por qué ayuda a comparar precio, riesgo y valor.",
    intro:
      "Probabilidad del modelo es una estimación generada por una capa estadística o analítica. Crea una visión independiente de las chances.",
    sections: [
      {
        title: "Cómo estima un modelo",
        body: [
          "Puede usar rendimiento, fuerza de equipos, localía, goles esperados, forma reciente y otros factores.",
          "El objetivo no es perfección, sino estimaciones consistentes, comparables y testeables.",
        ],
      },
      {
        title: "Modelo versus mercado",
        body: [
          "La casa publica precio. El modelo estima chance. Las diferencias crean oportunidades de análisis.",
        ],
      },
      {
        title: "Error común",
        body: [
          "Un error común es tratar el modelo como oráculo. Necesita calibración y contexto.",
        ],
      },
    ],
    productNote:
      "En prevIA, la probabilidad estimada es base para cuota justa y lectura de valor.",
    faq: [
      {
        question: "¿Garantiza resultados?",
        answer:
          "No. Es probabilística, no determinística.",
      },
      {
        question: "¿Por qué comparar modelo y mercado?",
        answer:
          "Porque las brechas pueden revelar distorsiones, valor o riesgo.",
      },
    ],
  },
};
